In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.DataFrame({
    "OriginalFeatures":[1,2,3,4,5,6,7],
    "CatagoricalFeatures":['A','B','A','B','A','B','A']
})
data

   OriginalFeatures CatagoricalFeatures
0                 1                   A
1                 2                   B
2                 3                   A
3                 4                   B
4                 5                   A
5                 6                   B
6                 7                   A

In [3]:
# one-hot encoding
data1=pd.get_dummies(data,columns=[ "CatagoricalFeatures"])
data1

   OriginalFeatures  CatagoricalFeatures_A  CatagoricalFeatures_B
0                 1                   True                  False
1                 2                  False                   True
2                 3                   True                  False
3                 4                  False                   True
4                 5                   True                  False
5                 6                  False                   True
6                 7                   True                  False

In [4]:
df=pd.read_csv("car data.csv")
df.head()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0

In [5]:
df.nunique()

Car_Name          98
Year              16
Selling_Price    156
Present_Price    147
Kms_Driven       206
Fuel_Type          3
Seller_Type        2
Transmission       2
Owner              3
dtype: int64

In [6]:
df.drop("Car_Name",axis=1,inplace=True)

In [7]:
df.head()

,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0

In [8]:
pd.get_dummies(df)

,Year,Selling_Price,Present_Price,Kms_Driven,Owner,Fuel_Type_CNG,Fuel_Type_Diesel,Fuel_Type_Petrol,Seller_Type_Dealer,Seller_Type_Individual,Transmission_Automatic,Transmission_Manual
0,2014,3.35,5.59,27000,0,False,False,True,True,False,False,True
1,2013,4.75,9.54,43000,0,False,True,False,True,False,False,True
2,2017,7.25,9.85,6900,0,False,False,True,True,False,False,True
3,2011,2.85,4.15,5200,0,False,False,True,True,False,False,True
4,2014,4.60,6.87,42450,0,False,True,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...
296,2016,9.50,11.60,33988,0,False,True,False,True,False,False,True
297,2015,4.00,5.90,60000,0,False,False,True,True,False,False,True
298,2009,3.35,11.00,87934,0,False,False,True,True,False,False,True
299,2017,11.50,12.50,9000,0,False,True,False,True,False,False,True
300,2016,5.30,5.90,5464,0,False,False,True,True,False,False,True

In [9]:
# Adding a new Features
room_length=[10,20,10,12,10,11]
room_breadth=[20,20,10,11,19,10]
room_type=["Big","Big","Normal",'Normal','Big','Normal']
data=pd.DataFrame({'Length':room_length,"Breadth":room_breadth,'Type':room_type})
data

   Length  Breadth    Type
0      10       20     Big
1      20       20     Big
2      10       10  Normal
3      12       11  Normal
4      10       19     Big
5      11       10  Normal

In [10]:
data["Area"]=data["Length"]*data["Breadth"]
data

   Length  Breadth    Type  Area
0      10       20     Big   200
1      20       20     Big   400
2      10       10  Normal   100
3      12       11  Normal   132
4      10       19     Big   190
5      11       10  Normal   110

In [11]:
data[data["Area"]>150]

   Length  Breadth Type  Area
0      10       20  Big   200
1      20       20  Big   400
4      10       19  Big   190

In [12]:
apartment_area=[4720,2430,4360,6142,7912,3960]
apartment_price=[216000000,121500000,218400000,194500000,307100000,395000000]
data4=pd.DataFrame({'Area':apartment_area,'Price':apartment_price})
data4

   Area      Price
0  4720  216000000
1  2430  121500000
2  4360  218400000
3  6142  194500000
4  7912  307100000
5  3960  395000000

In [13]:
data4['Price']=np.where(data4['Price']>100000000,'High',
                       np.where(data4['Price']<2000000000,'Low','Medium'))
data4

   Area Price
0  4720  High
1  2430  High
2  4360  High
3  6142  High
4  7912  High
5  3960  High

In [14]:
df1=pd.DataFrame({'A':[1,2,None],'B':[4,None,6]})
df2=pd.DataFrame({'A':[1,None,3],'B':[None,5,6]})
result=df1+df2
result

     A     B
0  2.0   NaN
1  NaN   NaN
2  NaN  12.0